### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by ivank** [scrutinizer-ci/scrutinizer#174]
Just found out about "Slack" which is an incredible team coordination. They have integrations for everything, except Scrutinizer. 

Are there any plans on this front? Travis has it built in with "notifications" configuration. Perhaps something like this is in order? 

If not I can write a composer package to do that with with the "custom commands", however there is no way to securely use a token and put it in a public repo. 

Ideally:

```
before_commands:
    - composer require "somepackage/package:0.1"
    - composer install

tools:
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=%mytoken%
```

something like this should work, I just have to figure out to make %mytoken% secret.
