### ISSUE TITLE
php_mess_detector: phpfilter: exclude_paths causes build config parse error

### ISSUE THREAD

**Issue by treffynnon** [scrutinizer-ci/scrutinizer#18]
I have the following build configuration and on save I get the following error (`Unable to parse at line 9 (near " filter:").`):

``` yaml
tools:
    php_cs_fixer: true
    php_code_sniffer:
        config:
            standard: PSR1
        filter:
            excluded_paths: ["tests/*"]
    php_mess_detector: true
        filter:
            excluded_paths: ["tests/*"]
    php_analyzer:
        filter:
            excluded_paths: ["tests/*"]
    sensiolabs_security_checker: true
```

This functionality is documented at https://scrutinizer-ci.com/docs/tools/php/mess-detector/
