### ISSUE TITLE
[bug] scrutinizer hangs on "Processing Results"

### ISSUE THREAD

**Issue by mAsT3RpEE** [scrutinizer-ci/scrutinizer#202]
[Scrutinizer-Build](https://scrutinizer-ci.com/g/mAsT3RpEE/BLW/)
[Travis-Build](http://travis-ci.org/mAsT3RpEE/BLW)
[Source](https://github.com/mAsT3RpEE/BLW)

Scrutinizer always hangs when "Processing results". This can last up to 30 minutes upon which scrutinizer-ci says build has timed out.

I've removed PHPUnit from composer.json. Also disabled PHP Change Tracking and PHP Code Similarity analysis.

.scrutinizer.yml

``` yml
imports:
  - php

before_commands:
  - composer install -n
  - composer dumpautoload -o

filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, app/*, build/*, temp/*, doc/*]

tools:
    external_code_coverage:
        timeout: 600
    php_analyzer: true
    php_code_sniffer:
        config:
            ruleset: config/ruleset.xml
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true
#    php_changetracking: true
#    php_sim: true    
```

composer.json

``` JSON
{
    "name" : "mast3rpee/blw",
    "description" : "Ajax/PHP/JavaScript Framework",
    "type" : "library",
    "homepage" : "http://mast3rpee.tk/projects/BLW",
    "license" : "MIT",
    "authors" : [{
            "name" : "Walter Otsyula",
            "email" : "wotsyula@mast3rpee.tk",
            "homepage" : "http://mast3rpee.tk",
            "role" : "Lead Developer"
        }
    ],
    "support" : {
        "email" : "support@mast3rpee.tk",
        "issues" : "https://github.com/mAsT3RpEE/BLW/issues",
        "source" : "https://github.com/mAsT3RpEE/BLW/tree/master",
        "wiki" : "http://mast3rpee.tk/api/BLW/"
    },
    "require" : {
        "php" : ">=5.3.3",
        "ext-dom" : "*",
        "ext-hash" : "*",
        "ext-json" : "*",
        "ext-mysqli" : "*",
        "ext-Phar" : "*",
        "ext-SPL" : "*",
        "ext-PDO" : "*",
        "ext-curl" : "*",
        "symfony/css-selector" : ">=2.4.4",
        "symfony/yaml" : ">=2.4.4",
        "psr/log" : ">=1.0.0",
        "monolog/monolog" : ">=1.9.1",
        "mrclay/minify" : "dev-master@dev",
        "zendframework/zend-db" : "dev-master@dev",
        "jeremeamia/SuperClosure" : "dev-master@dev"
    },
    "autoload" : {
        "psr-0" : {
            "BLW" : "src"
        }
    },
    "keywords" : [
        "BLW",
        "Framework"
    ]
}
```
