### ISSUE TITLE
Set environment variable for entire build

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#326]
How can I set an environment variable for the entire build? I can't find it in the docs.

The best I could find was [here](https://scrutinizer-ci.com/docs/configuration/build) but I don't want to override the command.

If I don't it throws: `Configuration was invalid: The child node "command" at path "before.0" must be configured.`

How do I set it in the "environment" build section?

There should be something like how [other](http://docs.shippable.com/en/latest/config.html#user-specified-environment-variables) ci [services](http://docs.travis-ci.com/user/environment-variables/) can define custom environment variables

**Comment by schmittjoh** [comment]
There are two options:

```
build:
    environment:
        variables: 
             FOO: BAR

    dependencies:
        before:
            - export FOO=BAR # via a regular unix command
```

You are right, we should have that in the docs though.
