### ISSUE TITLE
Not running tests

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#330]
Paid private repo with config:
```
build:
    environment:
        php: 5.4.30
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
```
However tests are not running:
![screen shot 2015-05-14 at 6 29 51 pm](https://cloud.githubusercontent.com/assets/3250776/7645267/43e97b82-fa67-11e4-8337-a5a114ece389.png)
