### ISSUE TITLE
Scrutinizer not identifying certain issues

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#333]
In the code there exists elements that are not picked up by scrutinizer as issues:
- `else if` should be `elseif`
- `public function name($var) {` should have the brace on a new line
- `$var = $a*$b;` should be `$var = $a * $b`

I haven't identified much else but this is the global configuration:
```yml
filter:
    excluded_paths:
        - 'tests/*'
tools:
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer: true
    php_cpd: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: false #min_mass: 50
    sensiolabs_security_checker: true
checks:
    php:
        fix_doc_comments: false
        no_new_line_at_end_of_file: false
        assignment_of_null_return: true
        avoid_closing_tag: true
        avoid_conflicting_incrementers: true
        avoid_corrupting_byteorder_marks: true
        avoid_duplicate_types: true
        avoid_fixme_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        avoid_superglobals: true
        avoid_tab_indentation: true
        avoid_todo_comments: true
        avoid_unnecessary_concatenation: true
        avoid_usage_of_logical_operators: true
        avoid_useless_overridden_methods: true
        blank_line_after_namespace_declaration: true
        classes_in_camel_caps: true
        closure_use_modifiable: true
        closure_use_not_conflicting: true
        code_rating: true
        deadlock_detection_in_loops: true
        deprecated_code_usage: true
        duplication: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        ensure_lower_case_builtin_functions: true
        fix_identation_4spaces: true
        fix_line_ending: true
        fix_linefeed: true
        fix_php_opening_tag: true
        fix_use_statements:
            order_alphabetically: false
            preserve_multiple: false
            preserve_blanklines: true
            remove_unused: true
        function_in_camel_caps: true
        function_body_start_on_new_line: true
        lowercase_basic_constants: true
        lowercase_php_keywords: true
        no_commented_out_code: true
        no_debug_code: true
        no_duplicate_arguments: true
        no_else_if_statements: true
        no_empty_statements: true
        no_error_suppression: true
        no_eval: true
        no_exit: true
        no_global_keyword: true
        no_goto: true
        no_long_variable_names:
            maximum: '50'
        no_non_implemented_abstract_methods: true
        no_property_on_interface: true
        no_short_method_names:
            minimum: '2'
        no_short_open_tag: true
        no_space_around_object_operator: true
        no_space_before_semicolon: true
        no_space_between_concatenation_operator: true
        no_space_inside_cast_operator: true
        no_trailing_whitespace: true
        no_underscore_prefix_in_methods: true
        no_underscore_prefix_in_properties: true
        no_unnecessary_function_call_in_for_loop: true
        no_unnecessary_if: true
        non_commented_empty_catch_block: true
        missing_arguments: true
        one_class_per_file: true
        optional_parameters_at_the_end: true
        parameter_non_unique: true
        parameters_in_camelcaps: true
        php5_style_constructor: true
        precedence_in_conditions: true
        precedence_mistakes: true
        prefer_unix_line_ending: true
        properties_in_camelcaps: true
        psr2_class_declaration: true
        psr2_control_structure_declaration: true
        psr2_switch_declaration: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        require_braces_around_control_structures: true
        require_php_tag_first: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        scope_indentation:
            spaces_per_level: '4'
        security_vulnerabilities: true
        simplify_boolean_return: true
        single_namespace_per_use: true
        space_after_cast: true
        spacing_around_conditional_operators: true
        spacing_around_non_conditional_operators: true
        spacing_of_function_arguments: true
        sql_injection_vulnerabilities: true
        too_many_arguments: true
        use_self_instead_of_fqcn: true
        use_statement_alias_conflict: true
        useless_calls: true
        unreachable_code: true
        unused_methods: true
        unused_parameters: true
        unused_properties: true
        unused_variables: true
        uppercase_constants: true
        variable_existence: true
        verify_access_scope_valid: true
coding_style:
    php:
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            do_while:
                opening: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
            while:
                opening: end-of-line
        spaces:
            around_operators:
                concatenation: false
            before_parentheses:
                closure_definition: true
        upper_lower_casing:
            constants:
                true_false_null: lower
            keywords:
                general: lower
```
