### ISSUE TITLE
Cannot disable inferred commands, breaking builds

### ISSUE THREAD

**Issue by tonglil** [scrutinizer-ci/scrutinizer#339]
After dependencies, Scrutinizer inferred a section called "Application" that it use to not infer.
This breaks our build as it goes to run scripts not meant for the CI server.

It would be simple to disable this but when I try to add the recommended override, the override stops inspections on start.
```yml
build:
    application:
        override:
            - true
```

![screen shot 2015-06-22 at 2 25 31 pm](https://cloud.githubusercontent.com/assets/3250776/8293503/97364e54-18ea-11e5-9bb5-da31bdd11d47.png)
