### ISSUE TITLE
Specifying rulesets for PHP Mess Detector (PHPMD) cause an exception

### ISSUE THREAD

**Issue by FlorianWolters** [scrutinizer-ci/scrutinizer#38]
Defining the following section in the `.scrutinizer.yml` configuration file does not work:

``` yml
  php_mess_detector:
    extensions:
      - php
    command: phpmd
    enabled: true
    config:
      rulesets:
        - codesize
        - controversial
        - design
        - naming
```

Running an inspection with that section causes the following error:

```
>   [Symfony\Component\Process\Exception\ProcessFailedException]

>   The command "phpmd '/tmp/phpmd_inputo7V5DW' xml 'codesize,controversial,design,naming'" failed.
```

I tested the `phpmd` command on my local machine and I think it is related to the `'` character. Simply ommit it and it should work, e.g.:

```
phpmd /tmp/phpmd_inputo7V5DW xml codesize,controversial,design,naming
```

My current workaround is to comment the `config` section for PHPMD in the configuration file:

``` yml
  php_mess_detector:
    extensions:
      - php
    command: phpmd
    enabled: true
#    config:
#      rulesets:
#        - codesize
#        - controversial
#        - design
#        - naming
```
