### ISSUE TITLE
phpcs custom_coding_standard from dependency in vendor/

### ISSUE THREAD

**Issue by john-n-smith** [scrutinizer-ci/scrutinizer#380]
We keep our phpcs standard in a separate repository as it's used across multiple projects. It can then be installed and it's version managed via composer.

As dependencies aren't installed when phpcs is ran, a config like the following fails:

```
checks:
    php:
        custom_coding_standard:
             ruleset_path: 'vendor/bin/graze/standards/phpcs.xml'
```

Example failure [here](https://scrutinizer-ci.com/g/graze/ciff-renderer/inspections/6da964ac-8244-4b47-be3c-5bd27a2ad5eb/log).

Is there a configuration directive to trigger dependency installation before code analysis, or the possibility of adding one?

This gives a single place to define phpcs' --standard for both scrutinizer and editors, rather than having to  use the `git_version` directive.
