### ISSUE TITLE
Disable tests

### ISSUE THREAD

**Issue by SerafimArts** [scrutinizer-ci/scrutinizer#395]
I do not need run tests in scrutinizer. But i didnt find this option (disable tests) in docs: https://scrutinizer-ci.com/docs/configuration/build

How fix this trouble?

**Comment by SerafimArts** [comment]
```yml
build:
    tests:
        override:
            command: "php -v"
```
It works, but... I think u can add this option, like: `build: { tests: false }`
